name: Build docker image

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/Animarum-IT/landing:latest
        docker push ghcr.io/animarum-it/landing:latest
